"""Security-headers audit (rule-based finding generator).

This module turns *web* artifacts (``curl`` ``web.http_meta`` and
``httpx`` ``web.http_probe``) into structured :class:`Finding` rows for
missing or weak security controls. The findings carry:

- ``source = FindingSource.RULE`` (deterministic, not AI)
- ``fact_or_inference = "fact"`` (the absence of a header is a fact)
- a CWE / OWASP / (sometimes) MITRE mapping
- a :class:`FindingEvidence` backref pointing at the originating
  artifact so reports can show the analyst exactly where the rule was
  triggered
- a short remediation placeholder

The audit deliberately does **not** raise on malformed inputs. Anything
it can't make sense of is silently dropped, so a single broken artifact
never poisons a whole session.

Rules implemented in v0.3:

| Rule                                              | Severity | CWE      | OWASP     |
|---------------------------------------------------|----------|----------|-----------|
| Missing HSTS (HTTPS only)                         | medium   | CWE-319  | A02:2021  |
| Weak HSTS ``max-age`` < 6 months (HTTPS only)     | low      | CWE-319  | A02:2021  |
| Missing Content-Security-Policy                   | low      | CWE-693  | A05:2021  |
| Missing X-Content-Type-Options: nosniff           | info     | CWE-693  | A05:2021  |
| Missing X-Frame-Options or CSP frame-ancestors    | low      | CWE-1021 | A05:2021  |
| Missing Referrer-Policy                           | info     | CWE-200  | A01:2021  |
| Server header leaks a version                     | info     | CWE-200  | A01:2021  |
| Cookie missing Secure (HTTPS only)                | low      | CWE-1004 | A02:2021  |
| Cookie missing HttpOnly                           | low      | CWE-1004 | A02:2021  |
| Cookie missing SameSite                           | info     | CWE-1275 | A02:2021  |
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from ..models.artifact import Artifact
from ..models.finding import Finding, FindingEvidence, FindingSeverity, FindingSource

# 6 months in seconds — Mozilla's recommended HSTS minimum.
HSTS_WEAK_MAX_AGE_THRESHOLD = 15_552_000

_VERSION_REGEX = re.compile(r"\d+\.\d+(?:\.\d+)?")


@dataclass
class _WebContext:
    """Everything the audit needs from one web artifact."""

    artifact_kind: str
    tool_name: str
    url: str | None
    scheme: str | None
    headers: dict[str, str]
    has_response: bool


def audit_security_headers(artifacts: list[Artifact]) -> list[Finding]:
    """Run every header-audit rule against every web artifact in ``artifacts``.

    Returns a flat list of :class:`Finding` rows. The function is idempotent
    and pure: callers can re-run it on the same artifacts and get the same
    findings (modulo the autogenerated finding IDs).

    Contexts whose underlying artifact carries no successful HTTP response
    (curl with no parsed hops, httpx with no status code) are skipped to
    avoid flooding the findings list with rules triggered by empty
    payloads. An empty *headers* dict on a successful response, however,
    legitimately fires every "missing X" rule.
    """
    findings: list[Finding] = []
    for art in artifacts:
        ctx = _context_for(art)
        if ctx is None:
            continue
        if not ctx.has_response:
            continue
        findings.extend(_audit_one(ctx))
    return findings


# ----- context extraction ---------------------------------------------------


def _context_for(art: Artifact) -> _WebContext | None:
    """Extract a normalized web context from a single artifact, or ``None``.

    Knows about both curl (``web.http_meta``) and httpx
    (``web.http_probe``). Anything else is ignored.
    """
    if art.kind == "web.http_meta":
        return _context_from_curl(art)
    if art.kind == "web.http_probe":
        return _context_from_httpx(art)
    return None


def _context_from_curl(art: Artifact) -> _WebContext:
    payload = art.payload or {}
    headers = _lowercase_headers(payload.get("final_headers") or {})
    url = _extract_url_from_command(art.raw_command)
    scheme = _scheme_from_url(url)
    has_response = payload.get("final_status") is not None
    return _WebContext(
        artifact_kind=art.kind,
        tool_name=art.tool_name,
        url=url,
        scheme=scheme,
        headers=headers,
        has_response=has_response,
    )


def _context_from_httpx(art: Artifact) -> _WebContext:
    payload = art.payload or {}
    return _WebContext(
        artifact_kind=art.kind,
        tool_name=art.tool_name,
        url=payload.get("url"),
        scheme=payload.get("scheme"),
        headers=_lowercase_headers(payload.get("headers") or {}),
        has_response=payload.get("status_code") is not None,
    )


def _lowercase_headers(headers: dict) -> dict[str, str]:
    out: dict[str, str] = {}
    for k, v in headers.items():
        if k is None:
            continue
        out[str(k).lower()] = str(v) if not isinstance(v, list) else ", ".join(str(x) for x in v)
    return out


def _extract_url_from_command(cmd: list[str] | None) -> str | None:
    if not cmd:
        return None
    for token in cmd:
        if isinstance(token, str) and (token.startswith("http://") or token.startswith("https://")):
            return token
    return None


def _scheme_from_url(url: str | None) -> str | None:
    if not url:
        return None
    if url.startswith("https://"):
        return "https"
    if url.startswith("http://"):
        return "http"
    return None


# ----- per-context rule runner ---------------------------------------------


def _audit_one(ctx: _WebContext) -> list[Finding]:
    rules = (
        _rule_hsts,
        _rule_csp,
        _rule_x_content_type_options,
        _rule_frame_protection,
        _rule_referrer_policy,
        _rule_server_version_leak,
        _rule_cookies,
    )
    out: list[Finding] = []
    for rule in rules:
        out.extend(rule(ctx))
    return out


def _evidence(ctx: _WebContext, header_name: str | None = None) -> list[FindingEvidence]:
    excerpt = None
    if header_name and header_name in ctx.headers:
        excerpt = f"{header_name}: {ctx.headers[header_name]}"
    elif header_name:
        excerpt = f"(no {header_name} header in response)"
    return [
        FindingEvidence(
            artifact_kind=ctx.artifact_kind,
            tool_name=ctx.tool_name,
            excerpt=excerpt,
            confidence=0.95,
        )
    ]


def _make_finding(
    *,
    ctx: _WebContext,
    title: str,
    summary: str,
    severity: FindingSeverity,
    cwe: list[str],
    owasp: list[str],
    remediation: str,
    evidence_header: str | None = None,
) -> Finding:
    return Finding(
        title=title,
        summary=summary,
        severity=severity,
        confidence=0.9,
        source=FindingSource.RULE,
        fact_or_inference="fact",
        related_tools=[ctx.tool_name],
        evidence=_evidence(ctx, header_name=evidence_header),
        cwe=cwe,
        owasp=owasp,
        recommended_next_steps=[
            "Confirm the missing/weak header against the application's threat model.",
            "Coordinate with the asset owner before treating this as a finding.",
        ],
        remediation=remediation,
        tags=["security-header"],
    )


# ----- individual rules -----------------------------------------------------


def _rule_hsts(ctx: _WebContext) -> list[Finding]:
    if ctx.scheme != "https":
        return []
    hsts = ctx.headers.get("strict-transport-security")
    if hsts is None:
        return [
            _make_finding(
                ctx=ctx,
                title="Missing Strict-Transport-Security header",
                summary=(
                    "The HTTPS response does not set a Strict-Transport-Security "
                    "header, leaving the client open to TLS downgrade attacks on "
                    "subsequent visits."
                ),
                severity=FindingSeverity.MEDIUM,
                cwe=["CWE-319"],
                owasp=["A02:2021"],
                remediation=(
                    "Send `Strict-Transport-Security: max-age=31536000; includeSubDomains` "
                    "(consider `; preload` once you commit to it)."
                ),
                evidence_header="strict-transport-security",
            )
        ]
    # Header present — check max-age strength.
    max_age = _parse_hsts_max_age(hsts)
    if max_age is not None and max_age < HSTS_WEAK_MAX_AGE_THRESHOLD:
        return [
            _make_finding(
                ctx=ctx,
                title="Weak Strict-Transport-Security max-age",
                summary=(
                    f"HSTS is enabled but the max-age value ({max_age}s) is shorter "
                    f"than the recommended minimum of {HSTS_WEAK_MAX_AGE_THRESHOLD}s "
                    "(6 months). A short max-age weakens the protection against "
                    "downgrade attacks."
                ),
                severity=FindingSeverity.LOW,
                cwe=["CWE-319"],
                owasp=["A02:2021"],
                remediation=(
                    "Increase max-age to at least 15552000 (6 months); 31536000 "
                    "(1 year) is the common production value."
                ),
                evidence_header="strict-transport-security",
            )
        ]
    return []


def _rule_csp(ctx: _WebContext) -> list[Finding]:
    if ctx.headers.get("content-security-policy"):
        return []
    return [
        _make_finding(
            ctx=ctx,
            title="Missing Content-Security-Policy header",
            summary=(
                "The response does not set a Content-Security-Policy header, "
                "removing the browser's primary defense against XSS and "
                "data-injection attacks."
            ),
            severity=FindingSeverity.LOW,
            cwe=["CWE-693"],
            owasp=["A05:2021"],
            remediation=(
                "Author a Content-Security-Policy that whitelists only the "
                "scripts, styles, and frame ancestors the application actually "
                "uses. Start in `Content-Security-Policy-Report-Only` mode."
            ),
            evidence_header="content-security-policy",
        )
    ]


def _rule_x_content_type_options(ctx: _WebContext) -> list[Finding]:
    value = ctx.headers.get("x-content-type-options")
    if value and value.strip().lower() == "nosniff":
        return []
    return [
        _make_finding(
            ctx=ctx,
            title="Missing X-Content-Type-Options: nosniff header",
            summary=(
                "Without `X-Content-Type-Options: nosniff` browsers may MIME-sniff "
                "responses, which can turn an arbitrary upload endpoint into a "
                "stored XSS sink."
            ),
            severity=FindingSeverity.INFO,
            cwe=["CWE-693"],
            owasp=["A05:2021"],
            remediation="Send `X-Content-Type-Options: nosniff` on every response.",
            evidence_header="x-content-type-options",
        )
    ]


def _rule_frame_protection(ctx: _WebContext) -> list[Finding]:
    if ctx.headers.get("x-frame-options"):
        return []
    csp = ctx.headers.get("content-security-policy") or ""
    if "frame-ancestors" in csp.lower():
        return []
    return [
        _make_finding(
            ctx=ctx,
            title="Missing clickjacking protection",
            summary=(
                "The response sets neither `X-Frame-Options` nor a CSP "
                "`frame-ancestors` directive, leaving the page vulnerable to "
                "framing/clickjacking by third-party origins."
            ),
            severity=FindingSeverity.LOW,
            cwe=["CWE-1021"],
            owasp=["A05:2021"],
            remediation=(
                "Set `X-Frame-Options: DENY` (or `SAMEORIGIN`) **and** "
                "`Content-Security-Policy: frame-ancestors 'none'`."
            ),
            evidence_header="x-frame-options",
        )
    ]


def _rule_referrer_policy(ctx: _WebContext) -> list[Finding]:
    if ctx.headers.get("referrer-policy"):
        return []
    return [
        _make_finding(
            ctx=ctx,
            title="Missing Referrer-Policy header",
            summary=(
                "Without an explicit Referrer-Policy the browser may leak the "
                "current URL (including any query-string secrets) to third-party "
                "origins via the Referer header."
            ),
            severity=FindingSeverity.INFO,
            cwe=["CWE-200"],
            owasp=["A01:2021"],
            remediation=(
                "Send `Referrer-Policy: strict-origin-when-cross-origin` (or "
                "stricter) on every response."
            ),
            evidence_header="referrer-policy",
        )
    ]


def _rule_server_version_leak(ctx: _WebContext) -> list[Finding]:
    server = ctx.headers.get("server")
    if not server:
        return []
    if not _VERSION_REGEX.search(server):
        return []
    return [
        _make_finding(
            ctx=ctx,
            title="Server header reveals software version",
            summary=(
                f"The Server response header advertises a version string "
                f"({server!r}). Version disclosure makes it cheaper for attackers "
                "to map known CVEs to this asset."
            ),
            severity=FindingSeverity.INFO,
            cwe=["CWE-200"],
            owasp=["A01:2021"],
            remediation=(
                "Strip the version (or the Server header entirely) at the "
                "reverse proxy / load balancer."
            ),
            evidence_header="server",
        )
    ]


def _rule_cookies(ctx: _WebContext) -> list[Finding]:
    raw = ctx.headers.get("set-cookie")
    if not raw:
        return []
    lower = raw.lower()
    findings: list[Finding] = []

    if ctx.scheme == "https" and "secure" not in lower:
        findings.append(
            _make_finding(
                ctx=ctx,
                title="Set-Cookie missing Secure attribute",
                summary=(
                    "An HTTPS response sets a cookie without the Secure flag, "
                    "so the cookie can be sent over a future plaintext request."
                ),
                severity=FindingSeverity.LOW,
                cwe=["CWE-1004"],
                owasp=["A02:2021"],
                remediation="Add `Secure` to every Set-Cookie on HTTPS responses.",
                evidence_header="set-cookie",
            )
        )

    if "httponly" not in lower:
        findings.append(
            _make_finding(
                ctx=ctx,
                title="Set-Cookie missing HttpOnly attribute",
                summary=(
                    "A response sets a cookie without HttpOnly, exposing it to "
                    "JavaScript and therefore to XSS payloads."
                ),
                severity=FindingSeverity.LOW,
                cwe=["CWE-1004"],
                owasp=["A02:2021"],
                remediation="Add `HttpOnly` to session cookies and any other cookie not consumed by JS.",
                evidence_header="set-cookie",
            )
        )

    if "samesite" not in lower:
        findings.append(
            _make_finding(
                ctx=ctx,
                title="Set-Cookie missing SameSite attribute",
                summary=(
                    "A response sets a cookie without SameSite, leaving it "
                    "vulnerable to cross-site request forgery."
                ),
                severity=FindingSeverity.INFO,
                cwe=["CWE-1275"],
                owasp=["A02:2021"],
                remediation="Add `SameSite=Lax` (or `Strict`) to every Set-Cookie.",
                evidence_header="set-cookie",
            )
        )

    return findings


# ----- helpers --------------------------------------------------------------


def _parse_hsts_max_age(value: str) -> int | None:
    """Extract the ``max-age`` integer from an HSTS header value."""
    for token in value.split(";"):
        token = token.strip().lower()
        if token.startswith("max-age="):
            raw = token.split("=", 1)[1].strip().strip('"')
            try:
                return int(raw)
            except ValueError:
                return None
    return None
